name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2

      # rsync コマンドでファイルをコピー
      - name: Sync files to container
        run: |
          rsync -av --progress ./ /root/ros2_ws/src/mypkg/

      # rsync 後のディレクトリ構造を確認
      - name: List files after sync
        run: |
          echo "Listing /root/ros2_ws/src/mypkg/ directory:"
          ls -R /root/ros2_ws/src/mypkg/

      # スクリプトの存在確認
      - name: Check if test.bash exists
        run: |
          if [ -f /root/ros2_ws/src/mypkg/test/test.bash ]; then
            echo "test.bash found"
          else
            echo -e "\033[31mERROR: test.bash not found!\033[0m"  # 赤色でエラー表示
            exit 1
          fi

      # スクリプトを実行
      - name: Build and test
        run: |
          bash -xv /root/ros2_ws/src/mypkg/test/test.bash /root

