name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest #前ページのコンテナを使うという宣言
    steps:
      - uses: actions/checkout@v2    #コンテナのカレントディレクトリにリポジトリを配置
      - name: build and test
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg/    # リポジトリの下をros2_ws下にコピー
          cd /root/ros2_ws # ↓追加のパッケージが必要なら実行前にrosdep
          source /opt/ros/foxy/setup.bash  # ROS 2のセットアップ
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y  # 必要な依存関係をインストール
          bash -xv ./src/mypkg/test/test.bash /root # パスを修正して実行

