name: test2

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the tests on

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest  # ROS 2 container image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3.7 python3.8 python3.9 python3.10

      - name: Install pip for all Python versions
        run: |
          for version in 3.7 3.8 3.9 3.10; do
            python${version} -m pip install --upgrade pip
          done

      - name: Build and test the package for each Python version
        run: |
          for version in 3.7 3.8 3.9 3.10; do
            sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${version} 1
            rsync -av ./ /root/ros2_ws/src/mypkg/
            cd /root/ros2_ws/
            bash -xv ./src/mypkg/test/test2.bash /root
          done

