name: Test Counter Processor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    container:
      image: ryuichiueda/ubuntu22.04-ros2
      options: --user=root

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up ROS 2 environment
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-colcon-common-extensions python3-rosdep
        python3 -m pip install -U setuptools
        rosdep update

    - name: Create ros2_ws workspace if necessary
      run: |
        # Create the workspace directory if not exists
        mkdir -p ~/ros2_ws/src/mypkg
        # Ensure that the workspace src folder is properly set up
        echo "Checking src/mypkg/test directory"
        ls ~/ros2_ws/src  # Check src directory
        ls ~/ros2_ws/src/mypkg  # Check mypkg directory
        ls ~/ros2_ws/src/mypkg/test  # Check test directory

    - name: Install dependencies
      run: |
        cd ~/ros2_ws
        rosdep install --from-paths src --ignore-src -r -y

    - name: Build the workspace
      run: |
        cd ~/ros2_ws
        colcon build

    - name: Source ROS 2 workspace
      run: |
        bash -c "source ~/ros2_ws/install/setup.bash"

    - name: Run counter_processor test script
      run: |
        cd ~/ros2_ws/src/mypkg/test
        ls  # List the contents of the test directory
        ./test_counter_processor.bash

