name: Run Tests and Publish Report

on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    
    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Sync files to container (if necessary)
      - name: Sync files to container
        run: |
          rsync -av --progress ./ /root/ros2_ws/src/mypkg/

      # Build the project
      - name: Build project
        run: |
          cd /root/ros2_ws
          colcon build

      # Run tests (ensure the tests output JUnit XML results)
      - name: Run tests
        run: |
          cd /root/ros2_ws
          colcon test --event-handlers console_cohesion+ --output-path build/test-results

      # Publish JUnit test results
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

