name: Test Counter Processor

on:
  push:
    branches:
      - main  # 必要に応じて、テストを実行したいブランチに変更

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest  # 使用するコンテナ

    steps:
      # リポジトリの内容をチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v2

      # ROS 2 ワークスペースのセットアップとビルド
      - name: Set up ROS 2 workspace
        run: |
          # ROS 2 のセットアップ
          apt-get update && apt-get install -y python3-colcon-common-extensions
          mkdir -p /root/ros2_ws/src/mypkg

          # ソースコードをコンテナ内にコピー
          rsync -av ./ /root/ros2_ws/src/mypkg/

          # ワークスペースをビルド
          cd /root/ros2_ws
          colcon build

          # ROS 2 環境のセットアップ
          bash -c "source /root/ros2_ws/install/setup.bash"  # bash -c で bash を使うように変更

      # ノード実行とログ確認
      - name: Run test script and check logs
        run: |
          # 実行前に環境を整える
          source /root/ros2_ws/install/setup.bash  # ここで再度source

          # テストスクリプトの実行
          bash -xv /root/ros2_ws/src/mypkg/test/test_counter_processor.bash /root

          # ログを確認する前に少し待機（ノードが実行されるまで）
          sleep 5

          # ノードのログが出力されているか確認
          timeout 10 tail -f /tmp/mypkg.log | grep "Generated" || echo "No log output"

