name: Test Counter Processor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    container:
      image: ryuichiueda/ubuntu22.04-ros2
      options: --user=root

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up ROS 2 environment
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-colcon-common-extensions python3-rosdep
        python3 -m pip install -U setuptools
        rosdep update

    - name: Create ros2_ws workspace
      run: |
        # Create the ros2_ws workspace if it doesn't exist
        mkdir -p ~/ros2_ws/src
        cd ~/ros2_ws/src
        # Checkout the repository into ros2_ws/src/mypkg
        ln -s /github/workspace mypkg
        ls ~/ros2_ws/src  # デバッグ: srcディレクトリの中身を表示
        ls ~/ros2_ws/src/mypkg  # デバッグ: mypkgディレクトリの中身を表示
        ls ~/ros2_ws/src/mypkg/test  # デバッグ: testディレクトリの中身を表示
        cd ~/ros2_ws

    - name: Install dependencies
      run: |
        cd ~/ros2_ws
        rosdep install --from-paths src --ignore-src -r -y

    - name: Build the workspace
      run: |
        cd ~/ros2_ws
        colcon build

    - name: Source ROS 2 workspace
      run: |
        bash -c "source ~/ros2_ws/install/setup.bash"

    - name: Run counter_processor test script
      run: |
        # デバッグ: testディレクトリの中身を再確認
        ls ~/ros2_ws/src/mypkg/test
        cd ~/ros2_ws/src/mypkg/test
        ./test_counter_processor.bash

