name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2

      # Python3 のバージョン確認
      - name: Check python3 version
        run: |
          python3 --version

      # Python3 のパス確認
      - name: Check if python3 exists
        run: |
          which python3

      # Python3 がインストールされていない場合、インストール
      - name: Install python3 if not present
        run: |
          if ! command -v python3 &> /dev/null; then
            echo "python3 not found, installing..."
            sudo apt update
            sudo apt install -y python3
          else
            echo "python3 is already installed"
          fi

      # `test.bash` の実行
      - name: build and test
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg/
          cd /root/ros2_ws/src/mypkg/
          bash -xv ./src/mypkg/test/test.bash /root

