name: test2

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the tests on

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest  # ROS 2 container image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies in the container
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-distutils

      - name: Build and test the package inside the container
        run: |
          # Copy the package source files to the workspace
          rsync -av ./ /root/ros2_ws/src/mypkg/

          # Navigate to the workspace
          cd /root/ros2_ws/

          # Run the test script inside the container
          bash -xv ./src/mypkg/test/test2.bash /root

  python_tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Install Python versions 3.7, 3.8, 3.9, 3.10 on host machine
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install -y python3.7 python3.8 python3.9 python3.10 python3-pip python3-distutils

      - name: Install pip for all Python versions
        run: |
          for version in 3.7 3.8 3.9 3.10; do
            python${version} -m ensurepip --upgrade
            python${version} -m pip install --upgrade pip
          done

      - name: Run tests for each Python version
        run: |
          for version in 3.7 3.8 3.9 3.10; do
            echo "Testing with Python${version}"
            sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${version} 1
            rsync -av ./ /root/ros2_ws/src/mypkg/
            cd /root/ros2_ws/
            bash -xv ./src/mypkg/test/test2.bash /root
          done

