name: ROS 2 Counter Processor Test

on:
  push:
    branches:
      - main  # メインブランチへのプッシュ時に実行
  pull_request:
    branches:
      - main  # プルリクエスト時にも実行

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ryuichiueda/ubuntu22.04-ros2  # 使用するDockerコンテナの指定
      options: --privileged  # Dockerコンテナ内で特権操作を許可

    steps:
    # リポジトリをクローンする
    - name: Checkout code
      uses: actions/checkout@v2

    # 必要なパッケージをインストール
    - name: Set up ROS 2 environment
      run: |
        sudo apt update
        sudo apt install -y python3-colcon-common-extensions python3-rosdep python3-pip

        # 既存のrosdepソースリストファイルがあれば削除
        sudo rm -f /etc/ros/rosdep/sources.list.d/20-default.list

        # rosdepを初期化
        sudo rosdep init
        rosdep update

    # ROS 2 ワークスペースをビルド
    - name: Build ROS 2 workspace
      run: |
        cd ros2_ws
        colcon build --symlink-install

    # ROS 2 ワークスペースをソース
    - name: Source ROS 2 setup
      run: |
        source ros2_ws/install/setup.bash

    # Bashスクリプトを実行（テスト）
    - name: Run Counter Processor Test
      run: |
        # 実行するbashスクリプトのパスを指定
        chmod +x ros2_ws/src/mypkg/test/test_counter_processor.bash
        ros2_ws/src/mypkg/test/test_counter_processor.bash
      env:
        ROS_LOCALHOST_ONLY: 1  # ローカルホスト限定でROS 2を動作させるため

    # テスト結果を表示（`timeout`コマンドで強制終了されないように設定）
    - name: Display ROS 2 logs
      run: |
        cat /tmp/mypkg.log

