name: Test Countdown Timer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.3
        with:
          distribution: humble

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-colcon-common-extensions

      - name: Build the package
        run: |
          cd ros2_ws
          colcon build

      - name: Source the setup script
        run: source ros2_ws/install/setup.bash

      - name: Run bash test
        run: bash ros2_ws/src/mypkg/test/test_countdown.bash

