name: test2

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the tests on

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest  # ROS 2 container image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3

      - name: Build and test the package
        run: |
          # Copy the package source files to the workspace
          rsync -av ./ /root/ros2_ws/src/mypkg/

          # Navigate to the workspace
          cd /root/ros2_ws/

          # Run the test script
          bash -xv ./src/mypkg/test/test2.bash /root
